# Generated by Django 3.0.7 on 2022-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='outstanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescripted_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
